// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdijfspwyfkvwthowufz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkaWpmc3B3eWZrdnd0aG93dWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NjM5NTgsImV4cCI6MjA5MDQzOTk1OH0.Sb8ezb8cCZ6uNf3wtVk1NoT92ZjxTxAP_AV5naJoP4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});